name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo --release --verbose
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ACPR Stats
        path: |
          target/release/acpr-stats-cli.exe
